/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/robots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Robot一覧取得（カーソルペジネーション） */
        get: operations["GetAll"];
        put?: never;
        /** @description Robot作成 */
        post: operations["Create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/robots/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Robot詳細取得 */
        get: operations["GetById"];
        /** @description Robot更新 */
        put: operations["Update"];
        post?: never;
        /** @description Robot削除 */
        delete: operations["Delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/robots/{id}/waypoint-logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Robotの走行履歴取得（カーソルペジネーション、Node情報を含む） */
        get: operations["GetWaypointLogs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/nodes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Node一覧取得（カーソルペジネーション、x, yを除外） */
        get: operations["GetAllNodes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/nodes/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Node詳細取得（x, yを除外） */
        get: operations["GetNodeById"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Robot取得用レスポンス */
        RobotResponse: {
            /**
             * Format: double
             * @description Robot ID
             */
            id: number;
            /** @description Robot name */
            name: string;
            /** @description Robot is active */
            isActive: boolean;
            /** @description Robot created at */
            createdAt: string;
            /** @description Robot updated at */
            updatedAt: string;
        };
        /** @description カーソルペジネーション付きレスポンス */
        CursorPaginatedResponse_RobotResponse_: {
            items: components["schemas"]["RobotResponse"][];
            nextCursor: string | null;
            hasNextPage: boolean;
        };
        /** @description Robot作成用リクエスト */
        RobotCreateRequest: {
            /** @description Robot name */
            name: string;
            /** @description Robot is active */
            isActive: boolean;
        };
        /** @description Robot更新用リクエスト */
        RobotUpdateRequest: {
            /** @description Robot name (optional) */
            name?: string;
            /** @description Robot is active (optional) */
            isActive?: boolean;
        };
        /** @description WaypointLog取得用レスポンス */
        WaypointLogResponse: {
            /**
             * Format: double
             * @description WaypointLog ID
             */
            id: number;
            /**
             * Format: double
             * @description Robot ID
             */
            robotId: number;
            /**
             * Format: double
             * @description Node ID
             */
            nodeId: number;
            /**
             * Format: double
             * @description Battery level
             */
            battery: number;
            /**
             * Format: date-time
             * @description その地点に到達した日時
             */
            reachedAt: string;
        };
        /** @description カーソルペジネーション付きレスポンス */
        CursorPaginatedResponse_WaypointLogResponse_: {
            items: components["schemas"]["WaypointLogResponse"][];
            nextCursor: string | null;
            hasNextPage: boolean;
        };
        /** @description 座標（Node の地理情報） */
        Position: {
            /** Format: double */
            x: number;
            /** Format: double */
            y: number;
        };
        /** @description Node取得用レスポンス */
        NodeResponse: {
            /**
             * Format: double
             * @description Node ID
             */
            id: number;
            /** @description Node name */
            name: string;
            /** @description 座標（x, y） */
            position: components["schemas"]["Position"];
        };
        /** @description カーソルペジネーション付きレスポンス */
        CursorPaginatedResponse_NodeResponse_: {
            items: components["schemas"]["NodeResponse"][];
            nextCursor: string | null;
            hasNextPage: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    GetAll: {
        parameters: {
            query?: {
                limit?: number;
                cursor?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CursorPaginatedResponse_RobotResponse_"];
                };
            };
        };
    };
    Create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RobotCreateRequest"];
            };
        };
        responses: {
            /** @description Ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RobotResponse"];
                };
            };
        };
    };
    GetById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RobotResponse"];
                };
            };
        };
    };
    Update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RobotUpdateRequest"];
            };
        };
        responses: {
            /** @description Ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RobotResponse"];
                };
            };
        };
    };
    Delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    GetWaypointLogs: {
        parameters: {
            query?: {
                limit?: number;
                cursor?: string;
            };
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CursorPaginatedResponse_WaypointLogResponse_"];
                };
            };
        };
    };
    GetAllNodes: {
        parameters: {
            query?: {
                limit?: number;
                cursor?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CursorPaginatedResponse_NodeResponse_"];
                };
            };
        };
    };
    GetNodeById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NodeResponse"];
                };
            };
        };
    };
}
